name = "talafutipolo"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "talafutipolo"
database_id = "7087ac6b-6417-48a4-9c7f-1d108057cd51"
