#!/usr/bin/env python3
"""Train a Tuvaluan↔English LoRA adapter in Tinker on top of gpt-oss-120b.

This is intentionally close to the Tinker cookbook `sl_loop.py`, but aimed at the
current repo layout and the dataset generated by `build_tinker_mt_data.py`.

Example:
    uv run python scripts/train_tinker_mt.py \
        --data data/finetune/tinker_mt/train_balanced.jsonl \
        --val-data data/finetune/tinker_mt/validation.jsonl \
        --model-name openai/gpt-oss-120b \
        --log-path logs/tinker/tvl-en-oss120b-lora-r32
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import os
import sys
import time
from pathlib import Path
from typing import Any


def add_cookbook_to_path(repo_root: Path) -> None:
    cookbook_root = repo_root / "vendor" / "tinker-cookbook"
    if cookbook_root.exists():
        sys.path.insert(0, str(cookbook_root))


REPO_ROOT = Path(__file__).resolve().parent.parent
add_cookbook_to_path(REPO_ROOT)

import datasets  # type: ignore  # noqa: E402
import tinker  # type: ignore  # noqa: E402
from tinker_cookbook import checkpoint_utils, model_info, renderers  # type: ignore  # noqa: E402
from tinker_cookbook.supervised.common import compute_mean_nll  # type: ignore  # noqa: E402
from tinker_cookbook.supervised.data import conversation_to_datum  # type: ignore  # noqa: E402
from tinker_cookbook.tokenizer_utils import get_tokenizer  # type: ignore  # noqa: E402

logger = logging.getLogger("train_tinker_mt")
logging.getLogger("httpx").setLevel(logging.WARN)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data",
        type=Path,
        default=REPO_ROOT / "data" / "finetune" / "tinker_mt" / "train_balanced.jsonl",
    )
    parser.add_argument(
        "--val-data",
        type=Path,
        default=REPO_ROOT / "data" / "finetune" / "tinker_mt" / "validation.jsonl",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="openai/gpt-oss-120b",
    )
    parser.add_argument(
        "--log-path",
        type=Path,
        default=REPO_ROOT / "logs" / "tinker" / "tvl-en-oss120b-lora-r32",
    )
    parser.add_argument("--base-url", type=str, default=None)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--learning-rate", type=float, default=1e-4)
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--max-length", type=int, default=2048)
    parser.add_argument("--lora-rank", type=int, default=32)
    parser.add_argument(
        "--train-on-what",
        choices=[
            "ALL_ASSISTANT_MESSAGES",
            "FINAL_ASSISTANT_MESSAGE",
        ],
        default="ALL_ASSISTANT_MESSAGES",
    )
    parser.add_argument("--save-every", type=int, default=100)
    parser.add_argument("--ttl-seconds", type=int, default=7 * 24 * 3600)
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument(
        "--do-final-val-loss",
        action="store_true",
        help="Compute validation loss at the end using the trained weights loaded from final state.",
    )
    return parser.parse_args()


def setup_logging(log_dir: Path) -> Path:
    log_dir.mkdir(parents=True, exist_ok=True)
    metrics_path = log_dir / "metrics.jsonl"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(log_dir / "train.log"),
        ],
    )
    return metrics_path


def append_jsonl(path: Path, row: dict[str, Any]) -> None:
    with path.open("a") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def load_split(path: Path, split_name: str) -> datasets.Dataset:
    ds = datasets.load_dataset("json", data_files={split_name: str(path)})
    assert isinstance(ds, datasets.DatasetDict)
    return ds[split_name]


def get_train_on_what(name: str) -> Any:
    enum_cls = renderers.TrainOnWhat
    try:
        return getattr(enum_cls, name)
    except AttributeError as exc:
        raise SystemExit(f"Unknown TrainOnWhat value: {name}") from exc


def mean_val_loss(
    *,
    dataset: datasets.Dataset,
    renderer: Any,
    training_client: Any,
    batch_size: int,
    max_length: int,
    train_on_what: Any,
) -> float:
    losses: list[float] = []
    n_batches = math.ceil(len(dataset) / batch_size)
    for batch_idx in range(n_batches):
        start = batch_idx * batch_size
        end = min((batch_idx + 1) * batch_size, len(dataset))
        rows = dataset.select(range(start, end))
        batch = [
            conversation_to_datum(row["messages"], renderer, max_length, train_on_what)
            for row in rows
        ]
        result = training_client.forward(batch, "cross_entropy").result()
        logprobs = [x["logprobs"] for x in result.loss_fn_outputs]
        weights = [d.loss_fn_inputs["weights"] for d in batch]
        losses.append(compute_mean_nll(logprobs, weights))
    return sum(losses) / len(losses) if losses else float("nan")


def main() -> None:
    args = parse_args()
    metrics_path = setup_logging(args.log_path)

    if not os.environ.get("TINKER_API_KEY"):
        raise SystemExit("TINKER_API_KEY must be set in the environment.")
    if not args.data.exists():
        raise SystemExit(f"Training data not found: {args.data}")
    if not args.val_data.exists():
        logger.warning("Validation data not found: %s", args.val_data)

    logger.info("Loading tokenizer and renderer for %s", args.model_name)
    tokenizer = get_tokenizer(args.model_name)
    renderer_name = model_info.get_recommended_renderer_name(args.model_name)
    renderer = renderers.get_renderer(renderer_name, tokenizer)
    logger.info("Using renderer: %s", renderer_name)

    train_on_what = get_train_on_what(args.train_on_what)
    train_dataset = load_split(args.data, "train")
    train_dataset = train_dataset.shuffle(seed=args.seed)
    logger.info("Loaded %d training examples", len(train_dataset))

    val_dataset = None
    if args.val_data.exists():
        val_dataset = load_split(args.val_data, "validation")
        logger.info("Loaded %d validation examples", len(val_dataset))

    service_client = tinker.ServiceClient(base_url=args.base_url)
    resume_info = checkpoint_utils.get_last_checkpoint(str(args.log_path))
    if resume_info:
        logger.info("Resuming from checkpoint state: %s", resume_info["state_path"])
        training_client = service_client.create_training_client_from_state_with_optimizer(
            resume_info["state_path"]
        )
        start_step = int(resume_info.get("step", resume_info.get("batch", 0)))
    else:
        logger.info(
            "Creating LoRA training client for %s with rank=%d",
            args.model_name,
            args.lora_rank,
        )
        training_client = service_client.create_lora_training_client(
            base_model=args.model_name,
            rank=args.lora_rank,
        )
        start_step = 0

    steps_per_epoch = math.ceil(len(train_dataset) / args.batch_size)
    total_steps = steps_per_epoch * args.epochs
    logger.info("Training for %d epochs, %d total steps", args.epochs, total_steps)

    for global_step in range(start_step, total_steps):
        epoch = global_step // steps_per_epoch
        step_in_epoch = global_step % steps_per_epoch
        batch_start = step_in_epoch * args.batch_size
        batch_end = min(batch_start + args.batch_size, len(train_dataset))
        rows = train_dataset.select(range(batch_start, batch_end))
        batch = [
            conversation_to_datum(row["messages"], renderer, args.max_length, train_on_what)
            for row in rows
        ]
        if not batch:
            continue

        if args.save_every > 0 and global_step > 0 and global_step % args.save_every == 0:
            checkpoint_utils.save_checkpoint(
                training_client=training_client,
                name=f"{global_step:06d}",
                log_path=str(args.log_path),
                kind="state",
                loop_state={"step": global_step},
                ttl_seconds=args.ttl_seconds,
            )

        start_time = time.time()
        lr_mult = max(0.0, 1.0 - (global_step / max(total_steps, 1)))
        current_lr = args.learning_rate * lr_mult
        adam_params = tinker.AdamParams(
            learning_rate=current_lr,
            beta1=0.9,
            beta2=0.95,
            eps=1e-8,
        )

        fwd_bwd_result = training_client.forward_backward(batch, loss_fn="cross_entropy").result()
        optim_result = training_client.optim_step(adam_params).result()

        train_logprobs = [x["logprobs"] for x in fwd_bwd_result.loss_fn_outputs]
        train_weights = [d.loss_fn_inputs["weights"] for d in batch]
        train_nll = compute_mean_nll(train_logprobs, train_weights)

        metrics: dict[str, Any] = {
            "step": global_step,
            "epoch": epoch,
            "step_in_epoch": step_in_epoch,
            "learning_rate": current_lr,
            "train_mean_nll": train_nll,
            "num_sequences": len(batch),
            "num_tokens": sum(d.model_input.length for d in batch),
            "time_total": time.time() - start_time,
        }
        if getattr(optim_result, "metrics", None):
            metrics.update(optim_result.metrics)
        append_jsonl(metrics_path, metrics)

        if global_step % 10 == 0:
            logger.info(
                "step=%d/%d epoch=%d train_nll=%.4f lr=%.6g batch=%d tokens=%d",
                global_step,
                total_steps,
                epoch,
                train_nll,
                current_lr,
                len(batch),
                metrics["num_tokens"],
            )

    checkpoint_utils.save_checkpoint(
        training_client=training_client,
        name="final",
        log_path=str(args.log_path),
        kind="both",
        loop_state={"step": total_steps},
        ttl_seconds=args.ttl_seconds,
    )
    logger.info("Saved final checkpoint under %s", args.log_path)

    if args.do_final_val_loss and val_dataset is not None and len(val_dataset) > 0:
        logger.info("Computing final validation loss...")
        final_resume = checkpoint_utils.get_last_checkpoint(str(args.log_path))
        if not final_resume:
            raise SystemExit("Expected a final checkpoint but none was found.")
        final_client = service_client.create_training_client_from_state(final_resume["state_path"])
        val_nll = mean_val_loss(
            dataset=val_dataset,
            renderer=renderer,
            training_client=final_client,
            batch_size=args.batch_size,
            max_length=args.max_length,
            train_on_what=train_on_what,
        )
        append_jsonl(metrics_path, {"step": total_steps, "validation_mean_nll": val_nll})
        logger.info("final validation_mean_nll=%.4f", val_nll)

    logger.info("Training completed")


if __name__ == "__main__":
    main()
